KETTLER_DEVICE_SERIAL=""

MQTT_CLIENT_ID="kettler"
MQTT_USERNAME="kettler"
MQTT_PASSWORD=""
MQTT_HOST="homeassistant"
MQTT_PORT=8883

IDLE_MQTT_UPDATE_TIME=60.0
BUSY_MQTT_UPDATE_TIME=5.0
IDLE_DEVICE_RESET_TIME=300.0
